'use strict';

exports.ROLE_ADMIN = 1;
exports.ROLE_USER = 2;

exports.RESERVATION_STATUS_PENDING = 0;
exports.RESERVATION_STATUS_CONFIRMED = 1;
exports.RESERVATION_STATUS_PAYED = 2;
exports.RESERVATION_STATUS_CANCELLED = 3;
exports.RESERVATION_STATUS_CLOSED = 4;

exports.PAYMENT_TYPE_CASH = 1;
exports.PAYMENT_TYPE_TRANSFER = 2;

exports.RESERVATION_TYPE_SITTING = 1;
exports.RESERVATION_TYPE_TRAINING = 2;
exports.RESERVATION_TYPE_EVALUATION = 3;
exports.RESERVATION_TYPE_CALL = 4;
exports.RESERVATION_TYPE_SHELTER = 5;